### ISSUE TITLE
Only .cts files listen in File Open menu

### ISSUE THREAD

**Issue by N7DR** [aardappel/treesheets#109]
Running 20161120~git7baabf39, which is the version in debian stable.

When I navigate to a directory to open a Treesheet file, there seems to be no way to list all the files in a directory. Only *.cts files are listed. There is an option to click the "*.cts" filter pattern, and on other programs that usually brings up other possible filter patterns; but in Treesheets, clicking that option does nothing, and the only available filter pattern seems to be "*.cts".

Thus, it seems that Treesheets currently essentially requires that the last four characters of a data file must be ".cts" if one is to find it easily (although if you happen to know the name of a Treesheet file, Treesheet will open it if you type it). So a Treesheets file called "Outline for book", for example CAN be opened, but not easily, since it's not displayable on the drop-down list.

I request that this behaviour be changed, so that there is an easy way to display all files in a directory, not just those that end in ".cts", preferably by adding a "All files *.*"  filter.

**Comment by aardappel** [comment]
That seems a limitation, sure, but are you saying you prefer to use a different extension with TreeSheets files? Why?

**Comment by N7DR** [comment]
Not at all; I'm saying that more than one filter should be provided.

Most (all?) of the other programs I use that provide a filter for file names allow me to click the filter and bring up a drop-down list of filters from which to choose -- and "All Files (*.*)" is typically one of them. (After all, there is a down-arrow on the filter, suggesting that I can click on it to obtain a drop down list; but no such list is present when I click the filter TreeSheets.)

As it stands right now, when I can't remember the name of a Treesheets file, I have to navigate to the directory, using either a file manager or the command line, and see what the names of the files in the directory are, so I can then type it in the TreeSheets "Open File" dialog. This is quite a painful process compared to simply selecting a different filter, then clicking on the filename.

I can include a screenshot if it's not obvious what I'm talking about.

**Comment by aardappel** [comment]
I don't think I understand the example, if the file you are searching for already has a .cts extension, then it should show up. Directories all show up too (at least on Windows), so not sure why you'd need a file manager.

That said, it turned out really easy to add an "All Files" option: https://github.com/aardappel/treesheets/commit/39f815ca69fe0a2528b438eb451c38a4b88e74bb

**Comment by sphh** [comment]
May I explain the reasoning behind @N7DR's request: On Unix/Linux systems, most of the time the file type is not determined by the extension, but by the contents of the file (see http://man7.org/linux/man-pages/man1/file.1.html). It is quite common do have files without the usual extension. The file still can be opened from a file manager, because the file manager determines the type (and the program to be used) not by the extension, but by the proper file type. (To get this work, an entry in the `magic` has to be written.)

On a Windows system the file manager relies on the extension to find the program. Two worlds – two concepts (I now don't say which one is the better ;-) )

**Comment by aardappel** [comment]
I spend my day-job entirely on Linux, and at least from what I can see, 99% of files I encounter have an extension, typically the same one as used on other OS-es. The exception being executables and a few text files. I'm sure Linux can determine file type by content but it doesn't seem to be relied upon too heavily.

Even if Linux doesn't strictly need it, having one is nice just in case the file is copied to other OSes or over the internet.

Either way, still don't see why you'd prefer to have no extension. It's not helping you with anything. You're not going to have an extension-less system no matter what you do :)

**Comment by sphh** [comment]
Sorry, your explanation sounded what I always here from Windows centred people ... 

No, you are right, filename extensions are helpful. But sometimes you want to open a file without an extension (e.g. if it was saved without extension; see #127).

I only tried to motivate to keep the change https://github.com/aardappel/treesheets/commit/39f815ca69fe0a2528b438eb451c38a4b88e74bb

**Comment by aardappel** [comment]
Ok, so we agree that saving should add an extension if none, but leave it alone if there is a custom extension, and that it should allow to load anything. The latter is already working so this issue can be closed.

**Comment by sphh** [comment]
Yes, that's how I know it from other programs. Thanks.
