### ISSUE TITLE
cannot add icon image to cell using toolbar

### ISSUE THREAD

**Issue by mhow2** [aardappel/treesheets#164]
Hi,

Running TS version "Sep  2 2019"

Selecting a cell then choose an icon image does nothing I can notice.
However I can add a regular picture through the edit menu (add image).

**Comment by aardappel** [comment]
Just tried this on Windows and it works just fine, either by selecting a new image from the drop down or double-clicking the existing one.

It even works with multiple cells selected.

What does not work is causing it to insert a cell when you only have a border selected, but that's kinda intentional.

**Comment by mhow2** [comment]
Running the latest x64 tarball for Linux. I select a cell, so it is highlighted, then I choose an image (icon) from the dropdown. Nothing happen. That's strange.

**Comment by mhow2** [comment]
Hi @aardappel,
I think I found the issue. The problem doesn't occur from the AppImage ("May 18 2020") but it does occur with http://strlen.com/treesheets/treesheets_linux64.tar.gz which is "Sep 2 2019". So I wonder if it's possible to consolidate the versions that are distributed from the website.

**Comment by aardappel** [comment]
I've updated the website with new download options:
http://strlen.com/treesheets/
