### ISSUE TITLE
Reproducible EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by EpicOrange** [aardappel/treesheets#170]
I've been bitten by this more than a couple of times. Here's how to reproduce it:

- new sheet
- copy anything
- paste to another cell
- undo
- shift-click another cell (which should expand selection, but instead crashes)

I use Mac, but this also crashes on Windows.

**Comment by aardappel** [comment]
Thanks for reporting! Fixed in https://github.com/aardappel/treesheets/commit/e04477e3d0a432508e3bd3af3dd31190bf52979a

shift+click emulates a drag action, and it was somehow not taking into account there could be an undo in between the start and the end of a drag, thus invalidating the start of the drag.

**Comment by EpicOrange** [comment]
Wow, that was unbelievably fast. Thank you for this wonderful tool!

**Comment by aardappel** [comment]
Your repro made it easy :)
