### ISSUE TITLE
Is it possible to integrate treesheets with Latex like freeplane

### ISSUE THREAD

**Issue by moebiuscurve** [aardappel/treesheets#184]
Firstly I am a huge fan of treesheets. For me, this is the most useful software ever. In fact, at most desperate times in my current job, this has been my savior. I organize everything in sheets.

I was wondering, if it was possible to integrate latex with treesheets so that it takes a latex equation and creates an inline image in the sheet. Currently, I use equalx to create images from latex equations and then paste them in treesheets.
If latex was integrated, I don't think I will ever use anything else for learning and maintaining my notes.

**Comment by aardappel** [comment]
Currently TreeSheets doesn't rely on any external applications to do anything, because doing so is typically tricky to get right in a cross-platform way.

What would probably be more practical is to add functions to the scripting language that allow you to a) run external commands (with the cell text as argument), b) load images and c) set them to cells, such that you could implement these yourself, and it would only have to work for your setup.

**Comment by GrimPixel** [comment]
Don't know much about it. I just found a repo and want to share. Maybe it helps.
https://github.com/NanoMichael/MicroTeX
