### ISSUE TITLE
Publish on FlatHub

### ISSUE THREAD

**Issue by catsout** [aardappel/treesheets#205]
Flatpak seems to be the new default way to distribute end-user software on many linux distribution. Flathub is the most popular repository of Flatpak.  

The work involves creating a manifest and then having it on a Github repository created by Flathub ( see https://github.com/flathub/flathub/wiki/App-Submission )  

This will solve the appimage's problem like https://github.com/aardappel/treesheets/issues/193

**Comment by catsout** [comment]
Some app examples using wxWidgets:
https://github.com/flathub/net.sourceforge.GrandOrgue
https://github.com/flathub/net.pcsx2.PCSX2

**Comment by aardappel** [comment]
It is very hard to tell for an outsider what matters in the big mess that is Linux packaging.

Certainly this project doesn't have the bandwidth to deal with packaging for any particular OS/distro/package format manually. Meaning, packing has to be automatic, uploading packages has to be automatic, versioning has to be automatic, and someone has to set that all up, otherwise it simply won't happen.

**Comment by catsout** [comment]
The flathub and flatpak can do it.  

Flatpak's manifest is similar to appimage's. Most of linux distributions support flatpak, and flatpak is more compatible than appimage.  
Flathub is a flatpak repo, which will provide the bandwidth.  
The automatic progress is done by flathub's bot, you only need to create new tag on github.
