### ISSUE TITLE
Large file may take several seconds to keep editing and saving

### ISSUE THREAD

**Issue by WangWei90** [aardappel/treesheets#206]
Hello, really thank you for this **wonderful software**, I use it daily for several weeks now.

I use treesheets to organize my images, so I can tag and write note for every image (contain image in .cts file is very convenient, use it as a little database). The file is 57M big, and treesheets perform really good in most time.  The save option still take several seconds, and it can be understood.

I have toggle off "write to .tmp" and "write to .bak" option, but during editing it will lag sometimes.

What should I do to, what is better way to organize something like this.

Thank you.

**Comment by aardappel** [comment]
While saving images as part of the file format is a convenient feature, I've never personally experiment with having it hold a LOT of images..

Certainly I can imagine saving is slow, because it will compress all images to PNG at that time. This could possibly be sped up by keeping a PNG copy of the image around after loading, so when saving it doesn't need to do that work again.

I would not expect it to slow down editing.. when it resizes the cell you're typing into, it possibly has to redraw all images visible on screen, but that shouldn't be slow, in fact I'd expect it to be faster than text.

Can you provide me with a download link for an example file that is slow? And an exact description of an editing operation that is slow (e.g. "put the cursor on this cell, then do this thing"..).

What platform?

**Comment by WangWei90** [comment]
Thank you for the answer.

I create a big file (pardon me, I use this file to test the stability, it turns out that treesheets is very stable).
https://drive.google.com/file/d/1yk4EpETE8zk7NH1U6PZda_tbWKiPt60t/view?usp=sharing

I hope you can get the file, and you can try to append some images at the end of the file.

I am on windows10.

Thank you.

**Comment by aardappel** [comment]
Saving that file is indeed very slow (almost 10 seconds), which is because what I mentioned above.

It will also save a temp copy when you switch away from it which is slow.

Other than that I've tried editing/text images at various locations and it is all very fast.. if there are any editing ops that are slow for you please give a precise description to reproduce.

**Comment by WangWei90** [comment]
> It will also save a temp copy when you switch away from it which is slow.

I encounter this, no other operations are lagging.

Can I disable write to a temp copy?

**Comment by aardappel** [comment]
Ok, that's weird, there was already the "Autosave to .tmp" menu option, but it wasn't used in the code! So I enabled it here: https://github.com/aardappel/treesheets/commit/413c24f8f3e8df2f79a047aeed6b870bd9b7dbac

So now turning that option off should stop it from saving when you de-activate TreeSheets window, and also no autosave every couple of minutes.

**Comment by aardappel** [comment]
Well, you're going to be extra happy because I solved this problem properly: by caching PNG data: https://github.com/aardappel/treesheets/commit/9d819e671563bed90a2ee4b43d4094a4c6ca0606

On your test file, it used to take 10.8 seconds to save, now it takes 0.3 seconds (a 30x speedup!!).

Now that it is super-fast, I recommend you just keep autosaving on.

Mind you, that was on my M.2 SSD drive, if you have slower storage it may take longer. But loading and saving times are now output in the status bar, so you can check for yourself.

**Comment by WangWei90** [comment]
I am super excited by this work, Thank you!

I will test it and it works great!

![image](https://user-images.githubusercontent.com/20700315/163739530-18c2d055-803c-438a-af19-befefd3091dd.png)

![image](https://user-images.githubusercontent.com/20700315/163739539-8bbafab5-dbe4-4e24-bf61-dbaf9d92f7f1.png)

**Comment by WangWei90** [comment]
I am closing this issue since I am satisfied with it.
