### ISSUE TITLE
Zoom issues

### ISSUE THREAD

**Issue by AntonBogun** [aardappel/treesheets#219]
I have created a basic test sheet that shows the problems with zoom.

[zoom_problems.zip](https://github.com/aardappel/treesheets/files/8534651/zoom_problems.zip)

the file is zipped because the cts extension is not supported by github.

Overview of problems without having to download the file:
![image](https://user-images.githubusercontent.com/70374466/164542204-6bce80d3-332a-498a-a6c7-119d295562cc.png)

**Comment by AntonBogun** [comment]
phew, resubmitting so many issues is quite a lot of work

**Comment by aardappel** [comment]
Fixing them is even more work :)

**Comment by aardappel** [comment]
This fixes bug #1: https://github.com/aardappel/treesheets/commit/38c5662659fdf7503fcd2bb7ba88d6576fb658d0
This fixes bug #3: https://github.com/aardappel/treesheets/commit/916a725b4cc1913d421b69a53e1bb991320bd2a8

Bug 2 is not really a bug, in so much as a simplification of the code. Will not fix for now.

"Note that in all cases when going down a pixel scale, the entire subgrid is selected rather than the top left cell (which is what happens normally).": yes, this is a side effect of bug #1, it was basically ensuring there was some selection when the actual selection was the parent. Should happen less now :)

**Comment by AntonBogun** [comment]
Could bug 2 could be fixed by simply zooming out once instead of resetting zoom?

**Comment by aardappel** [comment]
Likely, yes.
