### ISSUE TITLE
How to find the AppImage

### ISSUE THREAD

**Issue by mbetrifork** [aardappel/treesheets#255]
Well not exactly an issue per se, but on the treesheets home page https://strlen.com/treesheets/ there is a link to an AppImage download. But it leads to a page on Github that doesn't offer any AppImage to download - at least not as far as I could tell. 

An AppImage is a great way to quickly try out a new piece of software (that, or even better if you made a docker image) and I'm hoping you will make one available again.

**Comment by aardappel** [comment]
Ah, I'm afraid I deleted that release because it was very old.

It was added by @probonopd here: https://github.com/aardappel/treesheets/pull/134

Travis CI apparently hasn't run in 2 years. It seems Travis has changed their plans, and you can now only have a 30 day trial, or pay for it, or manually apply to be given credits as an OSS project.

I think it may be time to move this functionality to github actions instead? @probonopd how about it?

**Comment by probonopd** [comment]
> I think it may be time to move this functionality to github actions instead? @probonopd how about it?

Yes, Travis CI is no longer working properly anymore and a GitHub Action should be used instead.

**Comment by sphh** [comment]
I came here, because I was looking for an updated AppImage. Is one already available? Thanks.
