### ISSUE TITLE
F6 - inconsistent behaviour with definitions

### ISSUE THREAD

**Issue by toraritte** [aardappel/treesheets#272]
![F6-definition-issue](https://user-images.githubusercontent.com/1965782/194353657-3b2c943d-dad5-471b-9511-c7dbbc0e0df0.gif)

Simple cycling works great, but cycling through definition and subsequent uses seems arbitrary, and may be a pain when working on a large document to go back manually (or with <kbd>CTRL</kbd>-<kbd>F</kbd>).

This is not a big deal, just wanted to report it. Thanks so much for this app!

**Comment by aardappel** [comment]
F6 with different formatting will get you to the single definition if there is one, and to the first reference... it is not meant to get you to all references.. if that is a frequent use case, you're better off with no formatting differences and just cycle.

The problem is that it is context-less: if you're on a "definition" it doesn't know the history of "references" you may have already visited so it simply goes to the next one, much like cycling.

Ping-ponging between all "references" could be implemented, but it be much more complicated.. it would mean keeping a list of cells recently visited, always scanning all linked cells (rather than just going to the next), filtering those based on recent cells, adding to recent cells, at some point pruning recent cells (when? when the text changes?), and taking great care that if the document changes, this list of cells doesn't point to cells that have been deleted etc.

Right now, it all works without keeping such a list.

**Comment by toraritte** [comment]
> F6 with different formatting will get you to the single definition if there is one, and to the first reference

Got it, thanks! I'm experimenting with using TreeSheets for documentation prototyping, and immediately thought about using this feature with a glossary, but then again, simple cycling works just fine.

> The problem is that it is context-less: [..]

I would like to dive into the source at one point when time permits (hehe, good one..) so this info is definitely a valuable starting point. Thanks again!

**Comment by aardappel** [comment]
> I would like to dive into the source at one point when time permits

Please do :)
