### ISSUE TITLE
Linux scaling not working

### ISSUE THREAD

**Issue by aardappel** [aardappel/treesheets#372]
@t2b3 since you've worked on the DPI / scaling setting a lot recently.

A user is reporting the system is forcing external scaling on TreeSheets:

![image](https://user-images.githubusercontent.com/4663648/234071500-75256f81-0e6b-4972-bee1-3627c0992f44.png)

You get this with using 200% under Preferences > Displays > Scaling in Ubuntu MATE, though I imagine the problem may occur elsewhere too.

Ideally when the user sets that, we pick up on higher DPI and render this natively. Something is making this Ubuntu MATE window manager think we don't support scaling and is scaling for us.

**Comment by aardappel** [comment]
@t2b3 are you on the TreeSheets Discord btw? that's where this discussion came from

**Comment by McTank** [comment]
@t2b3 I'm the one who reported the issue.. let me know if I can help.

**Comment by t2b3** [comment]
Hi

I am currently ill. I think I might look into this in one or two weeks.

Have a nice Friday and a pleasant weekend
Kind regards
Tobias

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: jamwhammz ***@***.***>
Gesendet: Tuesday, April 25, 2023 6:08:35 AM
An: aardappel/treesheets ***@***.***>
Cc: Tobias Predel ***@***.***>; Mention ***@***.***>
Betreff: Re: [aardappel/treesheets] Linux scaling not working (Issue #372)


@t2b3<https://github.com/t2b3> I'm the one who reported the issue.. let me know if I can help.

**Comment by t2b3** [comment]
Hello

I tested under Xfce. They use the XSETTINGS protocol (https://specifications.freedesktop.org/xsettings-spec/xsettings-latest.html) to propagate changes I think, also including the change of the window scaling factor (see https://github.com/xfce-mirror/xfce4-settings/blob/c655eb9def0c3ea0724b6882130f2b4f711ff43b/xfsettingsd/xsettings.xml). But they just signal the change of gdk/WindowScalingFactor to the X client applications and let GDK (the GTK toolkit in the end) do the work.

In this way I do not experience any problems within TreeSheets. So the problem detailed above must be a MATE specific problem I guess.

Kind regards,
Tobias

**Comment by jamwhammz** [comment]
Hi Tobias,

Thanks for looking into it.

Incidentally I noticed there were some recent releases of TreeSheets mentioning "DPI" and I thought maybe I should try a more recent version. However I get an error mentioning "error while loading shared libraries" and also got that or similar with several bootable ISOs I tried for other distributions I tried today, e.g. Fedora. The only one that did run it was Linux Mint - and on that, it did run without pixelation. I think that was running Cinnamon rather than MATE.

Anyway thanks again!

**Comment by t2b3** [comment]
Hello @jamwhammz 

Thanks for your reply!

Unfortunately the recent changes are only related to the Windows operation system (MSW port) because the underlying framework (wxWidgets) only support certain HiDPI functionalities (e.g. generating events when DPI is changed) on the Windows platform.

As far as I know MATE builds upon GNOME 2 and Cinnamon upon GNOME 3. The (correct) scaling with the aforementioned XSETTINGS support was introduced with GTK 3 I think and that is why it is supported on Cinnamon but not in MATE I guess.

And the error because of incompatible libraries must be distribution-specific.

Kind regards,
Tobias

**Comment by jamwhammz** [comment]
Hi Tobias,

Curiosity got the better out of me, as I had downloaded both MATE and Cinnamon versions of Mint today, and I wasn't sure which one I had tried.

Anyway I just used the bootable version of Mint with MATE, and the latest TreeSheets runs, and there is no pixelation!
So I think its more of an Ubuntu MATE issue than strictly a MATE issue.

Or maybe its an Ubuntu issue, but its after 2am and I won't be doing any more testing today.

Thanks!

**Comment by t2b3** [comment]
Hi @jamwhammz 

Thanks for investigating, falsifying my assumption so I learnt something new again :-). Then it seems to be an Ubuntu-specific issue. 

Well, in this case nice and sunny greetings from Central Europe (it's evening now).

Kind regards,
Tobias

**Comment by jamwhammz** [comment]
Hi Tobias,

Thanks, I could do with some sun, or at least warmth right now.

I just had one more thought before bed - the version I am using on Ubuntu MATE was installed by apt, i.e. it is not the latest version. But on Mint, where I can run the latest version, it works.
So it could be a version thing, rather than a a distro thing.

Anyway I am downloading xubuntu and lubuntu overnight, and hopefully that will give more answers tomorrow.

Goodnight :-)

**Comment by jamwhammz** [comment]
Hi Tobias,

Just a quick update. I've tried bootable thumb drives of Ubuntu, Kubuntu, Lubuntu, Xubuntu, Debian Cinnamon, and Debian MATE, and none of them ran the latest Clang++ or G++ version of TreeSheets (all complaining about shared libraries). Mint Cinnamon and Mint MATE are still the only ones which I tested that do run.

Therefore I still can't say whether it is distribution related or TreeSheets version related.
I can only say that it's not desktop environment related.

However it sounds like the dependencies errors are a bigger problem than the pixelation. Maybe if those are solved, the pixelation won't be an issue any more.

Anyway I've spent too much time on the computer!
Enjoy the rest of your weekend.

Thanks
Jason

**Comment by t2b3** [comment]
Hi Jason

Thanks, have a nice weekend too!

The builds/releases provided on the website are created automatically by
means of this Continuous Integration workflow:

https://github.com/aardappel/treesheets/blob/master/.github/workflows/build.yml

According to https://github.com/actions/runner-images, ubuntu-latest is
currently Ubuntu 22.04.

Regards
Tobias

Am So., 7. Mai 2023 um 09:12 Uhr schrieb jamwhammz ***@***.***

**Comment by jamwhammz** [comment]
Hi Tobias,

Thanks for that - much to my amazement, I burnt Ubuntu MATE 22.04.2 to a thumb drive and the latest version of TreeSheets runs, and without pixelation! Yay!

I guess they must include extra stuff in the LTS versions.

Since I have already upgraded to 23.04, I will need to make some time on the weekend for a reinstall of the OS.

Thanks again for your help!

Regards,
Jason
